"""opkraevning datamodel

Revision ID: 839a6fd881cd
Revises: b1d790e291c7
Create Date: 2026-10-07 18:12:44.484410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '839a6fd881cd'
down_revision: Union[str, Sequence[str], None] = 'b1d790e291c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


KONTROLLER_RYKKER = r"""
CREATE OR REPLACE FUNCTION kontroller_rykker() RETURNS trigger AS $$
DECLARE
    f            invoices%ROWTYPE;
    forrige_sendt timestamptz;
    forrige_dato date;
    erhverv      boolean;
BEGIN
    -- Annullerede/fejlede rykkere sendes ikke og kontrolleres ikke.
    IF NEW.status NOT IN ('queued', 'sent') THEN
        RETURN NEW;
    END IF;

    SELECT * INTO f FROM invoices WHERE id = NEW.invoice_id;

    IF f.kind <> 'invoice' OR f.amount <= 0 THEN
        RAISE EXCEPTION 'Rykker afvist: faktura % er en kreditnota eller har intet beløb', f.invoice_no
            USING ERRCODE = 'check_violation';
    END IF;

    -- Højst 3 rykkere pr. ydelse – også medregnet dem, der blev sendt fra FarPay.
    IF NEW.step_no + f.prior_dunning_count > 3 THEN
        RAISE EXCEPTION 'Rykker afvist: faktura % ville få rykker nr. % (højst 3)',
            f.invoice_no, NEW.step_no + f.prior_dunning_count USING ERRCODE = 'check_violation';
    END IF;

    -- Mindst 10 dage efter forrige rykker (vores egen eller den seneste fra FarPay).
    IF NEW.step_no > 1 THEN
        SELECT sent_at INTO forrige_sendt FROM dunning_steps
        WHERE invoice_id = NEW.invoice_id AND step_no = NEW.step_no - 1 AND status = 'sent';
        IF forrige_sendt IS NULL THEN
            RAISE EXCEPTION 'Rykker afvist: rykker nr. % på faktura % er ikke sendt', NEW.step_no - 1, f.invoice_no
                USING ERRCODE = 'check_violation';
        END IF;
        forrige_dato := (forrige_sendt AT TIME ZONE 'Europe/Copenhagen')::date;
    ELSE
        forrige_dato := f.prior_last_dunning_at;
    END IF;
    IF forrige_dato IS NOT NULL AND (
         NEW.due_at < forrige_dato + 10
         OR (NEW.sent_at IS NOT NULL AND (NEW.sent_at AT TIME ZONE 'Europe/Copenhagen')::date < forrige_dato + 10)
       ) THEN
        RAISE EXCEPTION 'Rykker afvist: under 10 dage siden forrige rykker på faktura % (%)', f.invoice_no, forrige_dato
            USING ERRCODE = 'check_violation';
    END IF;

    -- Kompensationsbeløb kun i erhvervsforhold.
    IF NEW.compensation_amount > 0 THEN
        SELECT is_business INTO erhverv FROM debtors WHERE id = f.debtor_id;
        IF NOT coalesce(erhverv, false) THEN
            RAISE EXCEPTION 'Rykker afvist: kompensationsbeløb kun i erhvervsforhold (faktura %)', f.invoice_no
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;

    -- Ingen rykkere på en fordring hos inkasso.
    IF EXISTS (SELECT 1 FROM collection_cases
               WHERE invoice_id = NEW.invoice_id AND status NOT IN ('withdrawn', 'rejected')) THEN
        RAISE EXCEPTION 'Rykker afvist: faktura % har en aktiv inkassosag', f.invoice_no
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


def upgrade() -> None:
    """Opgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('extract(day FROM valid_from) = 1 AND extract(month FROM valid_from) IN (1, 7)', name=op.f('ck_reference_rates_gaelder_fra_1_jan_eller_1_jul')),
    sa.CheckConstraint('rate > -10 AND rate < 50', name=op.f('ck_reference_rates_rimelig_sats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_rates')),
    sa.UniqueConstraint('valid_from', name='uq_reference_rates_fra')
    )
    op.create_table('billing_periods',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=15), server_default='open', nullable=False),
    sa.Column('block_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'blocked' OR block_reason IS NOT NULL", name=op.f('ck_billing_periods_spaerret_har_begrundelse')),
    sa.CheckConstraint("status <> 'released' OR (released_at IS NOT NULL AND released_by IS NOT NULL)", name=op.f('ck_billing_periods_frigivet_af_et_menneske')),
    sa.CheckConstraint("status IN ('open', 'locked', 'draft', 'released', 'blocked')", name=op.f('ck_billing_periods_status_gyldig')),
    sa.CheckConstraint('extract(day FROM month) = 1', name=op.f('ck_billing_periods_maaned_er_den_1')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_billing_periods_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['released_by'], ['staff.id'], name=op.f('fk_billing_periods_released_by_staff'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_periods')),
    sa.UniqueConstraint('client_id', 'month', name='uq_billing_periods_kunde_maaned')
    )
    op.create_index(op.f('ix_billing_periods_client_id'), 'billing_periods', ['client_id'], unique=False)
    op.create_index(op.f('ix_billing_periods_released_by'), 'billing_periods', ['released_by'], unique=False)
    op.create_table('debtors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cvr', sa.String(length=8), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ean', sa.String(length=13), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('customer_group', sa.Integer(), nullable=True),
    sa.Column('preferred_channel', sa.String(length=10), nullable=True),
    sa.Column('is_business', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('blocked_from_dunning', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cvr IS NULL OR cvr ~ '^[0-9]{8}$'", name=op.f('ck_debtors_cvr_8_cifre')),
    sa.CheckConstraint("ean IS NULL OR ean ~ '^[0-9]{13}$'", name=op.f('ck_debtors_ean_13_cifre')),
    sa.CheckConstraint("preferred_channel IN ('email', 'ean', 'print', 'eboks')", name=op.f('ck_debtors_preferred_channel_gyldig')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_debtors_client_id_clients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debtors')),
    sa.UniqueConstraint('client_id', 'external_id', name='uq_debtors_kunde_ekstern')
    )
    op.create_index(op.f('ix_debtors_client_id'), 'debtors', ['client_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=15), server_default='invoice', nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_outstanding', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='DKK', nullable=False),
    sa.Column('ean', sa.String(length=13), nullable=True),
    sa.Column('status', sa.String(length=15), server_default='open', nullable=False),
    sa.Column('prior_dunning_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('prior_last_dunning_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'invoice' AND amount >= 0) OR (kind = 'credit_note' AND amount < 0)", name=op.f('ck_invoices_art_passer_til_fortegn')),
    sa.CheckConstraint("ean IS NULL OR ean ~ '^[0-9]{13}$'", name=op.f('ck_invoices_ean_13_cifre')),
    sa.CheckConstraint("kind IN ('invoice', 'credit_note')", name=op.f('ck_invoices_kind_gyldig')),
    sa.CheckConstraint("status IN ('open', 'paid', 'credited', 'written_off')", name=op.f('ck_invoices_status_gyldig')),
    sa.CheckConstraint('prior_dunning_count = 0 OR prior_last_dunning_at IS NOT NULL', name=op.f('ck_invoices_tidligere_rykker_har_dato')),
    sa.CheckConstraint('prior_dunning_count BETWEEN 0 AND 3', name=op.f('ck_invoices_tidligere_rykkere_0_3')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_invoices_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtors.id'], name=op.f('fk_invoices_debtor_id_debtors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('client_id', 'external_id', name='uq_invoices_kunde_ekstern')
    )
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_debtor_id'), 'invoices', ['debtor_id'], unique=False)
    op.create_index('ix_invoices_kunde_status_forfald', 'invoices', ['client_id', 'status', 'due_date'], unique=False)
    op.create_table('collection_cases',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('external_case_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=15), server_default='requested', nullable=False),
    sa.Column('principal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fees_included', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_included', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdraw_reason', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'withdrawn' OR (withdrawn_at IS NOT NULL AND withdraw_reason IS NOT NULL)", name=op.f('ck_collection_cases_tilbagekaldt_har_aarsag')),
    sa.CheckConstraint("status IN ('requested', 'open', 'paid', 'closed', 'withdrawn', 'rejected')", name=op.f('ck_collection_cases_status_gyldig')),
    sa.CheckConstraint('principal > 0', name=op.f('ck_collection_cases_hovedstol_positiv')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_collection_cases_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtors.id'], name=op.f('fk_collection_cases_debtor_id_debtors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_collection_cases_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['staff.id'], name=op.f('fk_collection_cases_requested_by_staff'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_cases')),
    sa.UniqueConstraint('idempotency_key', name='uq_collection_cases_idempotens')
    )
    op.create_index(op.f('ix_collection_cases_client_id'), 'collection_cases', ['client_id'], unique=False)
    op.create_index(op.f('ix_collection_cases_debtor_id'), 'collection_cases', ['debtor_id'], unique=False)
    op.create_index(op.f('ix_collection_cases_invoice_id'), 'collection_cases', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_collection_cases_requested_by'), 'collection_cases', ['requested_by'], unique=False)
    op.create_index('uq_collection_cases_aktiv_faktura', 'collection_cases', ['invoice_id'], unique=True, postgresql_where=sa.text("status NOT IN ('withdrawn', 'rejected')"))
    op.create_table('dunning_skips',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason IN ('betalt', 'krediteret', 'afskrevet', 'kreditnota', 'ikke_forfalden', 'indbetaling_seneste_2_bankdage', 'indbetaling_i_kassekladde', 'debitor_blokeret', 'afbetalingsordning', 'under_minimumsbeloeb', 'under_10_dage', 'max_3_rykkere', 'aktiv_inkassosag', 'fjernet_af_medarbejder')", name=op.f('ck_dunning_skips_reason_gyldig')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_dunning_skips_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dunning_skips'))
    )
    op.create_index(op.f('ix_dunning_skips_invoice_id'), 'dunning_skips', ['invoice_id'], unique=False)
    op.create_table('dunning_steps',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('step_no', sa.SmallInteger(), nullable=False),
    sa.Column('due_at', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('compensation_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='queued', nullable=False),
    sa.Column('document_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'sent', 'cancelled', 'failed')", name=op.f('ck_dunning_steps_status_gyldig')),
    sa.CheckConstraint('compensation_amount >= 0', name=op.f('ck_dunning_steps_kompensation_ikke_negativ')),
    sa.CheckConstraint('fee_amount >= 0 AND fee_amount <= 100', name=op.f('ck_dunning_steps_gebyr_hoejst_100')),
    sa.CheckConstraint('interest_amount >= 0', name=op.f('ck_dunning_steps_rente_ikke_negativ')),
    sa.CheckConstraint('step_no BETWEEN 1 AND 3', name=op.f('ck_dunning_steps_hoejst_3_rykkere')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_dunning_steps_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dunning_steps')),
    sa.UniqueConstraint('invoice_id', 'step_no', name='uq_dunning_steps_faktura_nr')
    )
    op.create_table('installment_plans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('installments', sa.SmallInteger(), nullable=False),
    sa.Column('first_due_date', sa.Date(), nullable=False),
    sa.Column('interval_days', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'defaulted', 'cancelled')", name=op.f('ck_installment_plans_status_gyldig')),
    sa.CheckConstraint('installments > 0', name=op.f('ck_installment_plans_mindst_en_rate')),
    sa.CheckConstraint('interval_days > 0', name=op.f('ck_installment_plans_interval_positivt')),
    sa.CheckConstraint('total_amount > 0', name=op.f('ck_installment_plans_beloeb_positivt')),
    sa.ForeignKeyConstraint(['created_by'], ['staff.id'], name=op.f('fk_installment_plans_created_by_staff'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_installment_plans_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installment_plans'))
    )
    op.create_index(op.f('ix_installment_plans_created_by'), 'installment_plans', ['created_by'], unique=False)
    op.create_index(op.f('ix_installment_plans_invoice_id'), 'installment_plans', ['invoice_id'], unique=False)
    op.create_index('uq_installment_plans_aktiv', 'installment_plans', ['invoice_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('invoice_payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('source', sa.String(length=15), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('economic', 'kassekladde', 'inkasso', 'farpay', 'manuel')", name=op.f('ck_invoice_payments_source_gyldig')),
    sa.CheckConstraint('amount <> 0', name=op.f('ck_invoice_payments_beloeb_ikke_nul')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_payments_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_payments')),
    sa.UniqueConstraint('invoice_id', 'source', 'external_id', name='uq_invoice_payments_kilde')
    )
    op.create_index(op.f('ix_invoice_payments_invoice_id'), 'invoice_payments', ['invoice_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('dunning_step_id', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='queued', nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('email', 'ean', 'print', 'eboks')", name=op.f('ck_deliveries_channel_gyldig')),
    sa.CheckConstraint("status <> 'sent' OR sent_at IS NOT NULL", name=op.f('ck_deliveries_sendt_har_tidspunkt')),
    sa.CheckConstraint("status IN ('queued', 'sent', 'failed', 'bounced')", name=op.f('ck_deliveries_status_gyldig')),
    sa.CheckConstraint('attempts BETWEEN 0 AND 3', name=op.f('ck_deliveries_hoejst_3_forsoeg')),
    sa.ForeignKeyConstraint(['dunning_step_id'], ['dunning_steps.id'], name=op.f('fk_deliveries_dunning_step_id_dunning_steps'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_deliveries_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries'))
    )
    op.create_index(op.f('ix_deliveries_dunning_step_id'), 'deliveries', ['dunning_step_id'], unique=False)
    op.create_index(op.f('ix_deliveries_invoice_id'), 'deliveries', ['invoice_id'], unique=False)
    op.create_table('fee_revenue',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('dunning_step_id', sa.BigInteger(), nullable=True),
    sa.Column('fee_type', sa.String(length=15), nullable=False),
    sa.Column('amount_charged', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_collected', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('accrued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billable_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_month', sa.Date(), nullable=True),
    sa.Column('collection_case_id', sa.BigInteger(), nullable=True),
    sa.Column('invoice_line_ref', sa.String(length=100), nullable=True),
    sa.Column('written_off_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('written_off_reason', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fee_type IN ('rykkergebyr', 'kompensation', 'morarente')", name=op.f('ck_fee_revenue_fee_type_gyldig')),
    sa.CheckConstraint("written_off_reason IN ('overdraget_til_inkasso', 'eftergivet', 'tilbagefoert', 'afskrevet')", name=op.f('ck_fee_revenue_written_off_reason_gyldig')),
    sa.CheckConstraint('(written_off_at IS NULL) = (written_off_reason IS NULL)', name=op.f('ck_fee_revenue_afskrivning_har_aarsag')),
    sa.CheckConstraint('amount_charged >= 0', name=op.f('ck_fee_revenue_paalagt_ikke_negativ')),
    sa.CheckConstraint('amount_collected >= 0', name=op.f('ck_fee_revenue_indbetalt_ikke_negativ')),
    sa.CheckConstraint('billing_month IS NULL OR extract(day FROM billing_month) = 1', name=op.f('ck_fee_revenue_maaned_er_den_1')),
    sa.CheckConstraint('collection_case_id IS NULL OR written_off_at IS NOT NULL OR billable_at IS NULL', name=op.f('ck_fee_revenue_inkasso_aldrig_fakturerbar')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_fee_revenue_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['collection_case_id'], ['collection_cases.id'], name=op.f('fk_fee_revenue_collection_case_id_collection_cases'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dunning_step_id'], ['dunning_steps.id'], name=op.f('fk_fee_revenue_dunning_step_id_dunning_steps'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_fee_revenue_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_revenue'))
    )
    op.create_index(op.f('ix_fee_revenue_client_id'), 'fee_revenue', ['client_id'], unique=False)
    op.create_index(op.f('ix_fee_revenue_collection_case_id'), 'fee_revenue', ['collection_case_id'], unique=False)
    op.create_index(op.f('ix_fee_revenue_dunning_step_id'), 'fee_revenue', ['dunning_step_id'], unique=False)
    op.create_index(op.f('ix_fee_revenue_invoice_id'), 'fee_revenue', ['invoice_id'], unique=False)
    op.create_index('ix_fee_revenue_kunde_maaned', 'fee_revenue', ['client_id', 'billing_month'], unique=False)
    op.create_table('installment_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_installment_lines_beloeb_positivt')),
    sa.ForeignKeyConstraint(['plan_id'], ['installment_plans.id'], name=op.f('fk_installment_lines_plan_id_installment_plans'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installment_lines'))
    )
    op.create_index(op.f('ix_installment_lines_plan_id'), 'installment_lines', ['plan_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('payment_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.String(length=15), nullable=False),
    sa.Column('dunning_step_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(target_type IN ('fee', 'compensation') AND dunning_step_id IS NOT NULL) OR (target_type = 'principal' AND dunning_step_id IS NULL) OR target_type = 'interest'", name=op.f('ck_payment_allocations_rykker_paa_gebyrer')),
    sa.CheckConstraint("target_type IN ('fee', 'compensation', 'interest', 'principal')", name=op.f('ck_payment_allocations_target_type_gyldig')),
    sa.CheckConstraint('amount <> 0', name=op.f('ck_payment_allocations_beloeb_ikke_nul')),
    sa.ForeignKeyConstraint(['dunning_step_id'], ['dunning_steps.id'], name=op.f('fk_payment_allocations_dunning_step_id_dunning_steps'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payment_allocations_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['invoice_payments.id'], name=op.f('fk_payment_allocations_payment_id_invoice_payments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocations'))
    )
    op.create_index(op.f('ix_payment_allocations_dunning_step_id'), 'payment_allocations', ['dunning_step_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_invoice_id'), 'payment_allocations', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    op.add_column('clients', sa.Column('payment_allocation_order', sa.String(length=20), server_default='costs_first', nullable=False))
    op.add_column('clients', sa.Column('fee_assignment_signed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('dunning_min_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('100'), nullable=False))
    op.add_column('clients', sa.Column('collection_mandate_signed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('auto_escalate_to_collection', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('clients', sa.Column('collection_min_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('500'), nullable=False))
    op.add_column('clients', sa.Column('collection_grace_days', sa.SmallInteger(), server_default=sa.text('10'), nullable=False))
    op.add_column('clients', sa.Column('fi_kreditornummer', sa.String(length=8), nullable=True))
    op.add_column('clients', sa.Column('business_customer_groups', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('clients', sa.Column('fee_income_account', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('interest_income_account', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_clients_fi_kreditornummer'), 'clients', ['fi_kreditornummer'])
    # ### end Alembic commands ###

    # --- Håndskrevet: CHECK-regler på clients (Alembic opdager dem ikke på en eksisterende tabel) ---
    op.create_check_constraint(op.f("ck_clients_payment_allocation_order_gyldig"), "clients",
                               "payment_allocation_order IN ('costs_first', 'principal_first')")
    op.create_check_constraint(op.f("ck_clients_rykker_minimum_ikke_negativ"), "clients", "dunning_min_amount >= 0")
    op.create_check_constraint(op.f("ck_clients_inkasso_minimum_ikke_negativ"), "clients", "collection_min_amount >= 0")
    op.create_check_constraint(op.f("ck_clients_inkasso_karens_mindst_10"), "clients", "collection_grace_days >= 10")
    op.create_check_constraint(op.f("ck_clients_fi_kreditornummer_8_cifre"), "clients",
                               "fi_kreditornummer IS NULL OR fi_kreditornummer ~ '^[0-9]{8}$'")

    # --- Håndskrevet: lovens grænser for rykkere (renteloven) som en trigger ---
    # Gælder for ALLE rykkere, der står i kø eller er sendt – uanset hvilken kode der lægger dem.
    # CHECK-reglerne på dunning_steps dækker gebyr <= 100 og step_no 1-3; her resten.
    op.execute(KONTROLLER_RYKKER)
    op.execute("""
        CREATE TRIGGER trg_kontroller_rykker
        BEFORE INSERT OR UPDATE ON dunning_steps
        FOR EACH ROW EXECUTE FUNCTION kontroller_rykker()
    """)


def downgrade() -> None:
    """Nedgrader databasen."""
    op.execute("DROP TRIGGER IF EXISTS trg_kontroller_rykker ON dunning_steps")
    op.execute("DROP FUNCTION IF EXISTS kontroller_rykker()")
    for navn in ("payment_allocation_order_gyldig", "rykker_minimum_ikke_negativ", "inkasso_minimum_ikke_negativ",
                 "inkasso_karens_mindst_10", "fi_kreditornummer_8_cifre"):
        op.drop_constraint(op.f(f"ck_clients_{navn}"), "clients", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_clients_fi_kreditornummer'), 'clients', type_='unique')
    op.drop_column('clients', 'interest_income_account')
    op.drop_column('clients', 'fee_income_account')
    op.drop_column('clients', 'business_customer_groups')
    op.drop_column('clients', 'fi_kreditornummer')
    op.drop_column('clients', 'collection_grace_days')
    op.drop_column('clients', 'collection_min_amount')
    op.drop_column('clients', 'auto_escalate_to_collection')
    op.drop_column('clients', 'collection_mandate_signed_at')
    op.drop_column('clients', 'dunning_min_amount')
    op.drop_column('clients', 'fee_assignment_signed_at')
    op.drop_column('clients', 'payment_allocation_order')
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_invoice_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_dunning_step_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_installment_lines_plan_id'), table_name='installment_lines')
    op.drop_table('installment_lines')
    op.drop_index('ix_fee_revenue_kunde_maaned', table_name='fee_revenue')
    op.drop_index(op.f('ix_fee_revenue_invoice_id'), table_name='fee_revenue')
    op.drop_index(op.f('ix_fee_revenue_dunning_step_id'), table_name='fee_revenue')
    op.drop_index(op.f('ix_fee_revenue_collection_case_id'), table_name='fee_revenue')
    op.drop_index(op.f('ix_fee_revenue_client_id'), table_name='fee_revenue')
    op.drop_table('fee_revenue')
    op.drop_index(op.f('ix_deliveries_invoice_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_dunning_step_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_invoice_payments_invoice_id'), table_name='invoice_payments')
    op.drop_table('invoice_payments')
    op.drop_index('uq_installment_plans_aktiv', table_name='installment_plans', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_installment_plans_invoice_id'), table_name='installment_plans')
    op.drop_index(op.f('ix_installment_plans_created_by'), table_name='installment_plans')
    op.drop_table('installment_plans')
    op.drop_table('dunning_steps')
    op.drop_index(op.f('ix_dunning_skips_invoice_id'), table_name='dunning_skips')
    op.drop_table('dunning_skips')
    op.drop_index('uq_collection_cases_aktiv_faktura', table_name='collection_cases', postgresql_where=sa.text("status NOT IN ('withdrawn', 'rejected')"))
    op.drop_index(op.f('ix_collection_cases_requested_by'), table_name='collection_cases')
    op.drop_index(op.f('ix_collection_cases_invoice_id'), table_name='collection_cases')
    op.drop_index(op.f('ix_collection_cases_debtor_id'), table_name='collection_cases')
    op.drop_index(op.f('ix_collection_cases_client_id'), table_name='collection_cases')
    op.drop_table('collection_cases')
    op.drop_index('ix_invoices_kunde_status_forfald', table_name='invoices')
    op.drop_index(op.f('ix_invoices_debtor_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_debtors_client_id'), table_name='debtors')
    op.drop_table('debtors')
    op.drop_index(op.f('ix_billing_periods_released_by'), table_name='billing_periods')
    op.drop_index(op.f('ix_billing_periods_client_id'), table_name='billing_periods')
    op.drop_table('billing_periods')
    op.drop_table('reference_rates')
    # ### end Alembic commands ###
