"""microsoft login paa staff

Revision ID: d5fc0dd99130
Revises: 5d936b47ecf9
Create Date: 2026-10-07 12:40:40.666882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fc0dd99130'
down_revision: Union[str, Sequence[str], None] = '5d936b47ecf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Opgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('microsoft_oid', sa.String(length=64), nullable=True))
    op.add_column('staff', sa.Column('sidst_logget_ind', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(op.f('uq_staff_microsoft_oid'), 'staff', ['microsoft_oid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Nedgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_staff_microsoft_oid'), 'staff', type_='unique')
    op.drop_column('staff', 'sidst_logget_ind')
    op.drop_column('staff', 'microsoft_oid')
    # ### end Alembic commands ###
