"""kontoudtog_fra paa clients

Revision ID: be29f9b7644c
Revises: d5fc0dd99130
Create Date: 2026-10-07 13:18:24.418309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be29f9b7644c'
down_revision: Union[str, Sequence[str], None] = 'd5fc0dd99130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Opgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('kontoudtog_fra', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Nedgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'kontoudtog_fra')
    # ### end Alembic commands ###
