"""indeks til seneste natkoersel

Revision ID: b1d790e291c7
Revises: 4f3be1e62b60
Create Date: 2026-10-07 13:46:35.922877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d790e291c7'
down_revision: Union[str, Sequence[str], None] = '4f3be1e62b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Opgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_log_kunde_handling_tid', 'audit_log', ['client_id', 'handling', 'tidspunkt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Nedgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_kunde_handling_tid', table_name='audit_log')
    # ### end Alembic commands ###
