"""fakturahoved, linjer og svaradresse

Revision ID: 147fe84aee17
Revises: 3975a850690d
Create Date: 2026-10-07 19:01:22.198375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '147fe84aee17'
down_revision: Union[str, Sequence[str], None] = '3975a850690d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Opgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('dunning_compensation_step', sa.SmallInteger(), server_default=sa.text('3'), nullable=False))
    op.add_column('clients', sa.Column('reply_to_email', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('order_no', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('other_ref', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('recipient', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('invoices', sa.Column('delivery', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('invoices', sa.Column('heading', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('text_line', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('invoices', sa.Column('lines_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # CHECK-regler opdages ikke af autogenerate.
    op.create_check_constraint("kompensation_paa_rykker_1_3", "clients", "dunning_compensation_step BETWEEN 1 AND 3")
    op.create_check_constraint("svar_email_gyldig", "clients",
                               r"reply_to_email IS NULL OR reply_to_email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'")


def downgrade() -> None:
    """Nedgrader databasen."""
    op.drop_constraint("svar_email_gyldig", "clients", type_="check")
    op.drop_constraint("kompensation_paa_rykker_1_3", "clients", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'lines_fetched_at')
    op.drop_column('invoices', 'lines')
    op.drop_column('invoices', 'text_line')
    op.drop_column('invoices', 'heading')
    op.drop_column('invoices', 'delivery')
    op.drop_column('invoices', 'recipient')
    op.drop_column('invoices', 'vat_amount')
    op.drop_column('invoices', 'net_amount')
    op.drop_column('invoices', 'other_ref')
    op.drop_column('invoices', 'order_no')
    op.drop_column('clients', 'reply_to_email')
    op.drop_column('clients', 'dunning_compensation_step')
    # ### end Alembic commands ###
