"""entries indeks paa bilagsnummer

Revision ID: 3867971909b7
Revises: 41b8dda17f9b
Create Date: 2026-10-04 20:06:58.757138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3867971909b7'
down_revision: Union[str, Sequence[str], None] = '41b8dda17f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Opgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_entries_kunde_bilag_dato', 'entries', ['client_id', 'bilagsnummer', 'dato'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Nedgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entries_kunde_bilag_dato', table_name='entries')
    # ### end Alembic commands ###
