"""fakturanummer paa entries og gruppe paa suppliers

Revision ID: 5d936b47ecf9
Revises: a443204570bb
Create Date: 2026-10-07 12:10:25.949656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d936b47ecf9'
down_revision: Union[str, Sequence[str], None] = 'a443204570bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Opgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('fakturanummer', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('gruppe', sa.Integer(), nullable=True))
    # Udfyld fakturanummer for poster, der allerede er hentet (fra det gemte rå svar).
    # Leverandørgruppen udfyldes ved næste synkronisering af leverandører.
    op.execute("""
        UPDATE entries
           SET fakturanummer = NULLIF(btrim(COALESCE(raa_data->>'supplierInvoiceNumber',
                                                     raa_data->>'invoiceNumber')), '')
         WHERE raa_data IS NOT NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Nedgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'gruppe')
    op.drop_column('entries', 'fakturanummer')
    # ### end Alembic commands ###
