"""accounting_years cache

Revision ID: 4f3be1e62b60
Revises: eff9bfaf5fb9
Create Date: 2026-10-07 13:21:22.433567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f3be1e62b60'
down_revision: Union[str, Sequence[str], None] = 'eff9bfaf5fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Opgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=20), nullable=False),
    sa.Column('fra', sa.Date(), nullable=True),
    sa.Column('til', sa.Date(), nullable=True),
    sa.Column('lukket', sa.Boolean(), nullable=True),
    sa.Column('sidst_set', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_accounting_years_client_id_clients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounting_years')),
    sa.UniqueConstraint('client_id', 'navn', name='uq_accounting_years_kunde_aar')
    )
    # Ny ressource i sync_state (Alembic opdager ikke ændrede CHECK-regler).
    op.drop_constraint(op.f('ck_sync_state_ressource_gyldig'), 'sync_state', type_='check')
    op.create_check_constraint(op.f('ck_sync_state_ressource_gyldig'), 'sync_state', "ressource IN ('accounts', 'customers', 'suppliers', 'entries', 'open_entries', 'invoices', 'journals', 'accounting_years')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Nedgrader databasen."""
    op.execute("DELETE FROM sync_state WHERE ressource = 'accounting_years'")
    op.drop_constraint(op.f('ck_sync_state_ressource_gyldig'), 'sync_state', type_='check')
    op.create_check_constraint(op.f('ck_sync_state_ressource_gyldig'), 'sync_state', "ressource IN ('accounts', 'customers', 'suppliers', 'entries', 'open_entries', 'invoices', 'journals')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounting_years')
    # ### end Alembic commands ###
