"""inkasso karens er fast for alle kunder

Revision ID: 5f13a2729721
Revises: 839a6fd881cd
Create Date: 2026-10-07 18:19:23.040851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f13a2729721'
down_revision: Union[str, Sequence[str], None] = '839a6fd881cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Opgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'collection_grace_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Nedgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('collection_grace_days', sa.SMALLINT(), server_default=sa.text('10'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
