"""rule_runs log over regelkoersler

Revision ID: 80b133628e44
Revises: 228563643322
Create Date: 2026-10-04 19:26:29.949840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b133628e44'
down_revision: Union[str, Sequence[str], None] = '228563643322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Opgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.Text(), nullable=False),
    sa.Column('rule_version', sa.SmallInteger(), nullable=False),
    sa.Column('koert_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fund', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("rule_code ~ '^[a-z0-9_]+$'", name=op.f('ck_rule_runs_rule_code_gyldig')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_rule_runs_client_id_clients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_runs'))
    )
    op.create_index('ix_rule_runs_kunde_regel_tid', 'rule_runs', ['client_id', 'rule_code', 'koert_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Nedgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rule_runs_kunde_regel_tid', table_name='rule_runs')
    op.drop_table('rule_runs')
    # ### end Alembic commands ###
