"""entries indeks til dubletreglen

Indeks på (client_id, kontonummer, beloeb, dato), så dubletreglen kan slå hvert par op
direkte. Erstatter ix_entries_kunde_konto, som det nye indeks dækker.

Revision ID: 41b8dda17f9b
Revises: 80b133628e44
Create Date: 2026-10-04 19:44:25.038230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b8dda17f9b'
down_revision: Union[str, Sequence[str], None] = '80b133628e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Opgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Nyt indeks først, så opslag på kunde + konto aldrig står uden indeks.
    op.create_index('ix_entries_kunde_konto_beloeb_dato', 'entries', ['client_id', 'kontonummer', 'beloeb', 'dato'], unique=False)
    op.drop_index(op.f('ix_entries_kunde_konto'), table_name='entries')
    op.execute("ANALYZE entries")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Nedgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entries_kunde_konto'), 'entries', ['client_id', 'kontonummer'], unique=False)
    op.drop_index('ix_entries_kunde_konto_beloeb_dato', table_name='entries')
    # ### end Alembic commands ###
