"""kontoudtog statements og statement_lines

Revision ID: a443204570bb
Revises: 3867971909b7
Create Date: 2026-10-07 11:33:58.020586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a443204570bb'
down_revision: Union[str, Sequence[str], None] = '3867971909b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Opgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('kilde', sa.String(length=20), nullable=False),
    sa.Column('kontonummer', sa.Integer(), nullable=True),
    sa.Column('modpart', sa.String(length=30), nullable=True),
    sa.Column('periode_fra', sa.Date(), nullable=False),
    sa.Column('periode_til', sa.Date(), nullable=False),
    sa.Column('fortegn', sa.String(length=10), nullable=False),
    sa.Column('kildefil', sa.Text(), nullable=True),
    sa.Column('oprettet', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fortegn IN ('samme', 'modsat')", name=op.f('ck_statements_fortegn_gyldig')),
    sa.CheckConstraint("kilde IN ('grossist', 'skattekonto', 'bank', 'andet')", name=op.f('ck_statements_kilde_gyldig')),
    sa.CheckConstraint("modpart ~ '^(debitor|kreditor):[0-9]+$'", name=op.f('ck_statements_modpart_gyldig')),
    sa.CheckConstraint('kontonummer IS NOT NULL OR modpart IS NOT NULL', name=op.f('ck_statements_har_modstykke')),
    sa.CheckConstraint('periode_fra <= periode_til', name=op.f('ck_statements_gyldig_periode')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_statements_client_id_clients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statements'))
    )
    op.create_index(op.f('ix_statements_client_id'), 'statements', ['client_id'], unique=False)
    op.create_table('statement_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('statement_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('linje_nr', sa.Integer(), nullable=False),
    sa.Column('dato', sa.Date(), nullable=False),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('tekst', sa.Text(), nullable=True),
    sa.Column('beloeb', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('raa_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('match_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('match_trin', sa.String(length=20), nullable=True),
    sa.CheckConstraint("match_trin IN ('bilag_beloeb', 'beloeb_dato')", name=op.f('ck_statement_lines_match_trin_gyldig')),
    sa.CheckConstraint('(match_entry_id IS NULL) = (match_trin IS NULL)', name=op.f('ck_statement_lines_match_hele')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_statement_lines_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['match_entry_id'], ['entries.id'], name=op.f('fk_statement_lines_match_entry_id_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], name=op.f('fk_statement_lines_statement_id_statements'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statement_lines')),
    sa.UniqueConstraint('statement_id', 'linje_nr', name='uq_statement_lines_udtog_linje')
    )
    op.create_index(op.f('ix_statement_lines_client_id'), 'statement_lines', ['client_id'], unique=False)
    op.create_index(op.f('ix_statement_lines_match_entry_id'), 'statement_lines', ['match_entry_id'], unique=False)
    op.create_index(op.f('ix_statement_lines_statement_id'), 'statement_lines', ['statement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Nedgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statement_lines_statement_id'), table_name='statement_lines')
    op.drop_index(op.f('ix_statement_lines_match_entry_id'), table_name='statement_lines')
    op.drop_index(op.f('ix_statement_lines_client_id'), table_name='statement_lines')
    op.drop_table('statement_lines')
    op.drop_index(op.f('ix_statements_client_id'), table_name='statements')
    op.drop_table('statements')
    # ### end Alembic commands ###
