"""rykkerindstillinger pr kunde

Revision ID: 3975a850690d
Revises: 5f13a2729721
Create Date: 2026-10-07 18:26:34.958882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3975a850690d'
down_revision: Union[str, Sequence[str], None] = '5f13a2729721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Opgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('dunning_mode', sa.String(length=10), server_default='off', nullable=False))
    op.add_column('clients', sa.Column('dunning_first_after_days', sa.SmallInteger(), server_default=sa.text('10'), nullable=False))
    op.add_column('clients', sa.Column('dunning_interval_days', sa.SmallInteger(), server_default=sa.text('10'), nullable=False))
    # ### end Alembic commands ###

    # Håndskrevet: CHECK-regler (Alembic opdager dem ikke på eksisterende tabeller).
    op.create_check_constraint(op.f("ck_clients_dunning_mode_gyldig"), "clients", "dunning_mode IN ('off', 'preview')")
    op.create_check_constraint(op.f("ck_clients_foerste_rykker_efter_forfald"), "clients",
                               "dunning_first_after_days >= 1")
    op.create_check_constraint(op.f("ck_clients_rykkerinterval_mindst_10"), "clients", "dunning_interval_days >= 10")
    op.drop_constraint(op.f("ck_dunning_skips_reason_gyldig"), "dunning_skips", type_="check")
    op.create_check_constraint(op.f("ck_dunning_skips_reason_gyldig"), "dunning_skips", "reason IN ('betalt', 'krediteret', 'afskrevet', 'kreditnota', 'ikke_forfalden', 'indbetaling_seneste_2_bankdage', 'indbetaling_i_kassekladde', 'debitor_blokeret', 'afbetalingsordning', 'under_minimumsbeloeb', 'under_10_dage', 'max_3_rykkere', 'aktiv_inkassosag', 'fjernet_af_medarbejder', 'rykker_i_koe')")
    op.drop_constraint(op.f("ck_invoice_payments_source_gyldig"), "invoice_payments", type_="check")
    op.create_check_constraint(op.f("ck_invoice_payments_source_gyldig"), "invoice_payments",
                               "source IN ('regnskab', 'kassekladde', 'inkasso', 'farpay', 'manuel')")


def downgrade() -> None:
    """Nedgrader databasen."""
    op.execute("DELETE FROM dunning_skips WHERE reason = 'rykker_i_koe'")
    op.drop_constraint(op.f("ck_invoice_payments_source_gyldig"), "invoice_payments", type_="check")
    op.create_check_constraint(op.f("ck_invoice_payments_source_gyldig"), "invoice_payments",
                               "source IN ('economic', 'kassekladde', 'inkasso', 'farpay', 'manuel')")
    op.drop_constraint(op.f("ck_dunning_skips_reason_gyldig"), "dunning_skips", type_="check")
    op.create_check_constraint(op.f("ck_dunning_skips_reason_gyldig"), "dunning_skips", "reason IN ('betalt', 'krediteret', 'afskrevet', 'kreditnota', 'ikke_forfalden', 'indbetaling_seneste_2_bankdage', 'indbetaling_i_kassekladde', 'debitor_blokeret', 'afbetalingsordning', 'under_minimumsbeloeb', 'under_10_dage', 'max_3_rykkere', 'aktiv_inkassosag', 'fjernet_af_medarbejder')")
    for navn in ("dunning_mode_gyldig", "foerste_rykker_efter_forfald", "rykkerinterval_mindst_10"):
        op.drop_constraint(op.f(f"ck_clients_{navn}"), "clients", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'dunning_interval_days')
    op.drop_column('clients', 'dunning_first_after_days')
    op.drop_column('clients', 'dunning_mode')
    # ### end Alembic commands ###
