"""journal_entries cache

Revision ID: eff9bfaf5fb9
Revises: be29f9b7644c
Create Date: 2026-10-07 13:19:29.103642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff9bfaf5fb9'
down_revision: Union[str, Sequence[str], None] = 'be29f9b7644c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Opgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('kladde_nummer', sa.Integer(), nullable=False),
    sa.Column('kladde_navn', sa.String(length=255), nullable=True),
    sa.Column('linje_id', sa.BigInteger(), nullable=True),
    sa.Column('bilagsnummer', sa.BigInteger(), nullable=True),
    sa.Column('dato', sa.Date(), nullable=True),
    sa.Column('konto', sa.Integer(), nullable=True),
    sa.Column('modkonto', sa.Integer(), nullable=True),
    sa.Column('modpart', sa.String(length=30), nullable=True),
    sa.Column('fakturanummer', sa.String(length=100), nullable=True),
    sa.Column('tekst', sa.Text(), nullable=True),
    sa.Column('beloeb', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valuta', sa.String(length=3), nullable=True),
    sa.Column('entry_type', sa.String(length=30), nullable=True),
    sa.Column('sidst_set', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_journal_entries_client_id_clients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries'))
    )
    op.create_index('ix_journal_entries_kunde', 'journal_entries', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Nedgrader databasen."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_journal_entries_kunde', table_name='journal_entries')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
